title: Euphony Music Austin
#logo: 
description: Organization based in Austin, Texas dedicated to spreading the joy of music and connecting young musicicans throughout the community
show_downloads: false
theme: jekyll-theme-minimal
